package view;

import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.JLabel;
import javax.swing.JFormattedTextField;
import java.awt.SystemColor;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JSplitPane;

public class GerenciarEventos extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarEventos
     */
    public GerenciarEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JPanel jPanel2 = new JPanel();
        jPanel2.setLayout(null);
        jPanel2.setPreferredSize(new Dimension(709, 523));
        jPanel2.setBackground(Color.WHITE);
        
        JPanel jPanel1 = new JPanel();
        jPanel1.setLayout(null);
        jPanel1.setBackground(new Color(9, 91, 176));
        jPanel1.setBounds(0, 0, 212, 725);
        jPanel2.add(jPanel1);
        
        JButton jButton20 = new JButton();
        jButton20.setIcon(new ImageIcon(GerenciarEventos.class.getResource("/view/icons/iconizer-editar.png")));
        jButton20.setText("Gerenciar agendamentos  ");
        jButton20.setForeground(Color.WHITE);
        jButton20.setFont(new Font("Segoe UI", Font.BOLD, 13));
        jButton20.setBorderPainted(false);
        jButton20.setBackground(new Color(36, 135, 219));
        jButton20.setBounds(0, 210, 223, 42);
        jPanel1.add(jButton20);
        
        JButton jButton7 = new JButton();
        jButton7.setIcon(new ImageIcon(GerenciarEventos.class.getResource("/view/icons/icons8-sair-26.png")));
        jButton7.setText(" Sair                        ");
        jButton7.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButton7.setForeground(Color.WHITE);
        jButton7.setFont(new Font("Segoe UI", Font.BOLD, 13));
        jButton7.setBorderPainted(false);
        jButton7.setBackground(new Color(36, 135, 219));
        jButton7.setBounds(0, 278, 223, 41);
        jPanel1.add(jButton7);
        
        JButton jButton18 = new JButton();
        jButton18.setIcon(new ImageIcon(GerenciarEventos.class.getResource("/view/icons/iconizer-agenda.png")));
        jButton18.setText("Agendar evento  ");
        jButton18.setForeground(Color.WHITE);
        jButton18.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jButton18.setBorderPainted(false);
        jButton18.setBackground(new Color(36, 135, 219));
        jButton18.setBounds(0, 143, 223, 43);
        jPanel1.add(jButton18);
        
        JButton jButton21 = new JButton();
        jButton21.setIcon(new ImageIcon(GerenciarEventos.class.getResource("/view/icons/icons8-casa-64.png")));
        jButton21.setText(" Página inicial      ");
        jButton21.setForeground(Color.WHITE);
        jButton21.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jButton21.setBorderPainted(false);
        jButton21.setBackground(new Color(36, 135, 219));
        jButton21.setBounds(0, 82, 223, 43);
        jPanel1.add(jButton21);
        
        JLabel lblGerenciarAgendamentos = new JLabel();
        lblGerenciarAgendamentos.setText("Gerenciar agendamentos");
        lblGerenciarAgendamentos.setForeground(new Color(9, 91, 176));
        lblGerenciarAgendamentos.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblGerenciarAgendamentos.setBackground(Color.WHITE);
        lblGerenciarAgendamentos.setBounds(317, 29, 253, 27);
        jPanel2.add(lblGerenciarAgendamentos);
        
        JLabel jLabel5 = new JLabel();
        jLabel5.setText("Alterar data");
        jLabel5.setForeground(new Color(36, 135, 219));
        jLabel5.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jLabel5.setBounds(317, 213, 85, 20);
        jPanel2.add(jLabel5);
        
        JLabel jLabel6 = new JLabel();
        jLabel6.setText("Alterar local");
        jLabel6.setForeground(new Color(36, 135, 219));
        jLabel6.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jLabel6.setBounds(317, 290, 104, 20);
        jPanel2.add(jLabel6);
        
        JLabel jLabel4 = new JLabel();
        jLabel4.setText("Alterar horário");
        jLabel4.setForeground(new Color(36, 135, 219));
        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jLabel4.setBounds(576, 213, 117, 20);
        jPanel2.add(jLabel4);
        
        JButton criarEvento = new JButton();
        criarEvento.setText("Criar evento");
        criarEvento.setForeground(Color.WHITE);
        criarEvento.setFont(new Font("Segoe UI", Font.BOLD, 14));
        criarEvento.setBorderPainted(false);
        criarEvento.setBackground(new Color(36, 135, 219));
        criarEvento.setBounds(460, 446, 212, 36);
        jPanel2.add(criarEvento);
        
        JFormattedTextField campoDescricao = new JFormattedTextField();
        campoDescricao.setHorizontalAlignment(SwingConstants.CENTER);
        campoDescricao.setForeground(new Color(36, 135, 219));
        campoDescricao.setBackground(Color.WHITE);
        campoDescricao.setBounds(317, 175, 471, 28);
        jPanel2.add(campoDescricao);
        
        JLabel lblNomeDoOrganizador = new JLabel();
        lblNomeDoOrganizador.setText("Agedandamentos");
        lblNomeDoOrganizador.setForeground(new Color(36, 135, 219));
        lblNomeDoOrganizador.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNomeDoOrganizador.setBounds(317, 85, 166, 20);
        jPanel2.add(lblNomeDoOrganizador);
        
        JLabel jLabel3 = new JLabel();
        jLabel3.setText("Alterar descrição");
        jLabel3.setForeground(new Color(36, 135, 219));
        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jLabel3.setBounds(317, 149, 129, 20);
        jPanel2.add(jLabel3);
        
        JLabel lblDescrio = new JLabel();
        lblDescrio.setText("Deseja editar ou excluir?");
        lblDescrio.setForeground(new Color(36, 135, 219));
        lblDescrio.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblDescrio.setBounds(576, 85, 224, 20);
        jPanel2.add(lblDescrio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 528, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        JButton btnNewButton = new JButton("Editar");
        btnNewButton.setForeground(SystemColor.textHighlight);
        btnNewButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnNewButton.setBounds(574, 114, 85, 27);
        jPanel2.add(btnNewButton);
        
        JButton btnExcluir = new JButton("Excluir");
        btnExcluir.setForeground(SystemColor.textHighlight);
        btnExcluir.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnExcluir.setBounds(681, 115, 85, 27);
        jPanel2.add(btnExcluir);
        
        JComboBox comboBox = new JComboBox();
        comboBox.setBounds(317, 115, 202, 24);
        jPanel2.add(comboBox);
        
        JFormattedTextField campoDescricao_1 = new JFormattedTextField();
        campoDescricao_1.setHorizontalAlignment(SwingConstants.CENTER);
        campoDescricao_1.setForeground(new Color(36, 135, 219));
        campoDescricao_1.setBackground(Color.WHITE);
        campoDescricao_1.setBounds(317, 243, 471, 28);
        jPanel2.add(campoDescricao_1);
        
        JFormattedTextField campoDescricao_1_1 = new JFormattedTextField();
        campoDescricao_1_1.setHorizontalAlignment(SwingConstants.CENTER);
        campoDescricao_1_1.setForeground(new Color(36, 135, 219));
        campoDescricao_1_1.setBackground(Color.WHITE);
        campoDescricao_1_1.setBounds(317, 323, 471, 28);
        jPanel2.add(campoDescricao_1_1);
        
        JLabel lblNomeDoOrganizador_1 = new JLabel();
        lblNomeDoOrganizador_1.setText("Nome do organizador");
        lblNomeDoOrganizador_1.setForeground(new Color(36, 135, 219));
        lblNomeDoOrganizador_1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNomeDoOrganizador_1.setBounds(317, 361, 202, 20);
        jPanel2.add(lblNomeDoOrganizador_1);
        
        JFormattedTextField campoDescricao_1_1_1 = new JFormattedTextField();
        campoDescricao_1_1_1.setHorizontalAlignment(SwingConstants.CENTER);
        campoDescricao_1_1_1.setForeground(new Color(36, 135, 219));
        campoDescricao_1_1_1.setBackground(Color.WHITE);
        campoDescricao_1_1_1.setBounds(317, 395, 471, 28);
        jPanel2.add(campoDescricao_1_1_1);
        
       
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarEventos().setVisible(true);
            }
        });
    }
}